<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyTitle>RebuildBotPlugin</AssemblyTitle>
    <Product>RagnarokRebuildTcp Automation Bot Plugin</Product>
    <Copyright>Copyright © 2026</Copyright>
    <Version>1.0.0.0</Version>
    <FileVersion>1.0.0.0</FileVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RebuildSharedData">
      <HintPath>..\RoRebuildServer\RebuildSharedData\bin\Release\netstandard2.1\RebuildSharedData.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="warps.json" />
  </ItemGroup>

</Project>
